## Sorting arrays in Numpy
Numpy, short for Numerical Python, is the fundamental package required for hight performance scientific computing and its best library to learn and apply on data science career.



In [3]:
import numpy as np

In [9]:
names = np.array(['F', 'C', 'A', 'G'])
weights = np.array([20.8, 93.2, 53.4, 61.8])

sort(weights)

array([ 20.8,  53.4,  61.8,  93.2])

In [10]:
#argsort
ordered_indices = np.argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int64)

In [11]:
weights[ordered_indices]

array([ 20.8,  53.4,  61.8,  93.2])

In [13]:
names[ordered_indices]

array(['F', 'A', 'G', 'C'],
      dtype='<U1')

In [15]:
data = np.array([20.8,  93.2,  53.4,  61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int64)

In [16]:
# sort data
data.sort()
data

array([ 20.8,  53.4,  61.8,  93.2])

In [17]:
# 2d array
a = np.array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[ 0.2,  0.1,  0.5],
       [ 0.4,  0.8,  0.3],
       [ 0.9,  0.6,  0.7]])

In [18]:
sort(a)

array([[ 0.1,  0.2,  0.5],
       [ 0.3,  0.4,  0.8],
       [ 0.6,  0.7,  0.9]])

In [20]:
# sort by column
sort(a, axis = 0)

array([[ 0.2,  0.1,  0.3],
       [ 0.4,  0.6,  0.5],
       [ 0.9,  0.8,  0.7]])

In [22]:
# search sort
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])

In [24]:
np.searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int64)