## Matrix Object in Numpy
Numpy, short for Numerical Python, is the fundamental package required for hight performance scientific computing and its best library to learn and apply on data science career.

This is just little illustration.

<img style="float: left;" src="https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages1346880.png" width=400 height=200>

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
A = np.mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [3]:
A = np.mat('1,2,4;2,5,3;7,8,9')
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [5]:
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.array([[10,20], 
              [30,40]])

np.bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

In [10]:
x = np.array([[4], [2], [3]])
x

array([[4],
       [2],
       [3]])

In [11]:
A * x

matrix([[20],
        [27],
        [71]])

In [12]:
print(A * A.I)

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   6.24500451e-17]
 [  2.22044605e-16  -8.32667268e-17   1.00000000e+00]]


In [13]:
print(A ** 3)

[[ 443  654  678]
 [ 489  731  741]
 [1269 1866 1919]]
