# BASIC FUNCTION IN NUMPY

In [1]:
# import numpy library
import numpy as np
# version of numpy
np.__version__

'1.22.4'

In [2]:
# list of method in numpy
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [3]:
# how many method
len(dir(np))

600

 define a array/ ndarray

In [4]:
arr = np.array([2, 5, 8 , 10])

In [5]:
arr

array([ 2,  5,  8, 10])

In [6]:
# define array with tuple
arr2 = np.array((2,4,6,8))

In [7]:
arr2

array([2, 4, 6, 8])

In [8]:
# define 2 dimention array or 3-dimention array
arr_2d = np.array([[2,4,6,8],[3,6,9,12]])
arr_3d = np.array([[[2,4,6,8],[3,6,9,12]], [[4,8,12,16],[5,10,15,20]]])
# we can define n-dirmention array

In [9]:
arr_2d

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [10]:
arr_3d

array([[[ 2,  4,  6,  8],
        [ 3,  6,  9, 12]],

       [[ 4,  8, 12, 16],
        [ 5, 10, 15, 20]]])

find dimention of array

In [11]:
arr_3d.ndim

3

indexing in array

In [12]:
# index start with 0 
print(arr[2]) # 1d array indexing - access 3 element of array = 8

print(arr_2d[0,2]) #2d array indexing - access 3 element of first arr = 6

# 3d array indexing - access 3 element of first arr in second arr = 12
print(arr_3d[1, 0, 2]) 

8
6
12


In [13]:
# negative indexing
print(arr[-1]) # 1d array - access last element of array = 10

print(arr_2d[-2, -1]) # 2d array - access last elment of first array = 8

# 3d array - access second last element of first array in second array = 12
print(arr_3d[1, -2, -2]) 

10
8
12


In [14]:
# we can create zero value array
# create 2d array with 3 element
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# similiar zeros , we can create one value array
# 3d array with 7 element
np.ones([3,7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# also create a empty
em = np.empty((1,5))
em

array([[2.12199579e-314, 1.34958932e-311, 1.58101007e-321,
        3.79442416e-321, 0.00000000e+000]])

In [17]:
# define array with arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# arnage[start, end, defferent]
rang = np.arange(5,50,10)

In [19]:
rang

array([ 5, 15, 25, 35, 45])

In [20]:
# define array with linspace 
# similiar arange but define same space between elements linspace[star, end, no_of_element]
lspace = np.linspace(5,50,10)

In [21]:
lspace

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

##  Tranform Array 

In [22]:
# tranfrom array - convert row to column and column to row
arr_2d

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [23]:
arr_2d.T

array([[ 2,  3],
       [ 4,  6],
       [ 6,  9],
       [ 8, 12]])

## SLICING OF NUMPY ARRAY 

In [24]:
# slicing of 1d array[start:end]
print(arr[1:3]) # 5, 8

# slicing of 2d array[arr_index or [start:end], start:end]
print(arr_2d[1,:2]) # print 2 starting element of second arr

# slicing of 3d array[arr_index, arr_index, start:end]
# print second and third element of all array inside first arr
# [4,6][6,9]
print('\n')
print(arr_3d[0,:,1:3])

[5 8]
[3 6]


[[4 6]
 [6 9]]


## Data Types

find data types

In [25]:
print(arr.dtype)
print(arr_2d.dtype)
print(arr_3d.dtype)

int32
int32
int32


define data types

In [26]:
new_arr = np.array([5,10,15,20], dtype = 'i8') # i8 = integer 4 byte

In [27]:
new_arr.dtype

dtype('int64')

convert data type

In [28]:
float_arr = new_arr.astype('f')
float_arr

array([ 5., 10., 15., 20.], dtype=float32)

## Copy and View and Revel

make copy of a array

In [29]:
copy_arr = arr_2d.copy()
copy_arr

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [30]:
# make change in copy array not effect original array
copy_arr[0,-1] = 10  # 8 = 10
copy_arr

array([[ 2,  4,  6, 10],
       [ 3,  6,  9, 12]])

make view, change in view effect original array

In [31]:
view = arr.view()
view

array([ 2,  5,  8, 10])

In [32]:
view[1] = 6
print(view)
print(arr)

[ 2  6  8 10]
[ 2  6  8 10]


convert multi dimension array in 1d flat array - original array

In [33]:
ndarr = np.array([[3,4,8,12,5],[9,21, 3, 15, 8]])
ndarr.ravel()

array([ 3,  4,  8, 12,  5,  9, 21,  3, 15,  8])

In [34]:
ndarr.ravel()

array([ 3,  4,  8, 12,  5,  9, 21,  3, 15,  8])

In [35]:
# we define order [ C: row-major order(default), F: column-major order, ]
ndarr.ravel(order='F')

array([ 3,  9,  4, 21,  8,  3, 12, 15,  5,  8])

## Size, Byte, Shape and Reshape

print size of array

In [36]:
print(arr.size)
print(arr_2d.size)
print(arr_3d.size)

4
8
16


print bytes of array

In [37]:
print(arr.nbytes)
print(arr_2d.nbytes)
print(arr_3d.nbytes)

16
32
64


In [38]:
np.shape

<function numpy.shape(a)>

shape return tuple- number of element according dimensions

In [39]:
print(arr.shape)      # 1d array - 4 element
print(arr_2d.shape)   # 2d array - 2 arr inside arr, 4 element in every arr
print(arr_3d.shape)   # 3d arr - 2 element arr, 2 element arr, 4 element

(4,)
(2, 4)
(2, 2, 4)


reshape a arr(3d array to 1d array)

In [40]:
reshape_arr = arr_3d.reshape(16) 

In [41]:
reshape_arr

array([ 2,  4,  6,  8,  3,  6,  9, 12,  4,  8, 12, 16,  5, 10, 15, 20])

In [42]:
# convert a multidimensional array into 1d array
arr1d = arr_3d.reshape(-1)

In [43]:
arr1d

array([ 2,  4,  6,  8,  3,  6,  9, 12,  4,  8, 12, 16,  5, 10, 15, 20])

In [44]:
reshape_arr1d = arr.reshape(2,2) # 1d array 2d array

In [45]:
reshape_arr1d

array([[ 2,  6],
       [ 8, 10]])

## Array Iterating

python iteration with for loop 

In [46]:
# iterate 2d array
for arr in arr_2d:
    for a in arr:
        print(a)

2
4
6
8
3
6
9
12


In [47]:
# iterate 3d array
for arr in arr_3d:
    for ar in arr:
        for a in ar:
            print(a)

2
4
6
8
3
6
9
12
4
8
12
16
5
10
15
20


numpy iteration - nditer()

In [48]:
# 2d array 
for a in np.nditer(arr_2d):
    print(a)

2
4
6
8
3
6
9
12


In [49]:
# 3d array
for a in np.nditer(arr_3d):
    print(a)

2
4
6
8
3
6
9
12
4
8
12
16
5
10
15
20


iterate multi dimension using flat

In [50]:
# flat - 1d iterator over multi dimension array, converts multi dimension array in 1d array then iterate
for a in arr_3d.flat:
    print(a)

2
4
6
8
3
6
9
12
4
8
12
16
5
10
15
20


In [51]:
# check index 
for i, a in enumerate(arr_3d.flat):
    print(f"Index : {i},  Element : {a}")

Index : 0,  Element : 2
Index : 1,  Element : 4
Index : 2,  Element : 6
Index : 3,  Element : 8
Index : 4,  Element : 3
Index : 5,  Element : 6
Index : 6,  Element : 9
Index : 7,  Element : 12
Index : 8,  Element : 4
Index : 9,  Element : 8
Index : 10,  Element : 12
Index : 11,  Element : 16
Index : 12,  Element : 5
Index : 13,  Element : 10
Index : 14,  Element : 15
Index : 15,  Element : 20


change value using flat [index]

In [52]:
arr_3d.flat[10] = 7  
print(arr_3d)

[[[ 2  4  6  8]
  [ 3  6  9 12]]

 [[ 4  8  7 16]
  [ 5 10 15 20]]]


In [53]:
# change value in range flat[start:end]
arr_3d.flat[4:8] = 5
print(arr_3d)

[[[ 2  4  6  8]
  [ 5  5  5  5]]

 [[ 4  8  7 16]
  [ 5 10 15 20]]]


iteration with ndenumerate

In [54]:
for idx, a in np.ndenumerate(arr_3d):
    print(idx, a)

(0, 0, 0) 2
(0, 0, 1) 4
(0, 0, 2) 6
(0, 0, 3) 8
(0, 1, 0) 5
(0, 1, 1) 5
(0, 1, 2) 5
(0, 1, 3) 5
(1, 0, 0) 4
(1, 0, 1) 8
(1, 0, 2) 7
(1, 0, 3) 16
(1, 1, 0) 5
(1, 1, 1) 10
(1, 1, 2) 15
(1, 1, 3) 20


## Join Numpy Arrays

join two array with concatenate

In [55]:
arr = np.array([2, 5, 8 , 10])
arr2 = np.array((2,4,6,8))
np.concatenate((arr, arr2))

array([ 2,  5,  8, 10,  2,  4,  6,  8])

In [56]:
np.concatenate((arr2,arr))

array([ 2,  4,  6,  8,  2,  5,  8, 10])

In [57]:
arr_2d_ = np.array([[4,8,12,16],[5,10,15,20]])

In [58]:
arr_2d_

array([[ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])

In [59]:
arr_2d

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

concatenate with axis 

In [60]:
np.concatenate((arr_2d, arr_2d_), axis=1) # add in row

array([[ 2,  4,  6,  8,  4,  8, 12, 16],
       [ 3,  6,  9, 12,  5, 10, 15, 20]])

In [61]:
np.concatenate((arr_2d, arr_2d_), axis = 0) #add in column

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])

join array with stack - it join arr not elements

In [62]:
# 1d array + 1d array = 2d array - we can pass axis
stack = np.stack((arr2, arr), axis = 1)
stack

array([[ 2,  2],
       [ 4,  5],
       [ 6,  8],
       [ 8, 10]])

In [63]:
# check join array dimension
stack.ndim

2

In [64]:
stack_ = np.stack((arr_2d, arr_2d_)) 
stack_

array([[[ 2,  4,  6,  8],
        [ 3,  6,  9, 12]],

       [[ 4,  8, 12, 16],
        [ 5, 10, 15, 20]]])

In [65]:
# check join array dimension - 3d array
stack_.ndim

3

In [66]:
# use hstack for join element of array in row
np.hstack((arr,arr2))

array([ 2,  5,  8, 10,  2,  4,  6,  8])

In [67]:
# vstack for join element of array in column
np.vstack((arr,arr2))

array([[ 2,  5,  8, 10],
       [ 2,  4,  6,  8]])

In [68]:
# dstack - join according depth 
# 4 element in array - 4 arr inside arr
np.dstack((arr,arr2))

array([[[ 2,  2],
        [ 5,  4],
        [ 8,  6],
        [10,  8]]])

## Split Array

In [69]:
# split a arr in multiple arr
# array_split(array, split_part)
np.array_split(arr, 2)

[array([2, 5]), array([ 8, 10])]

In [70]:
np.array_split(arr,3)

[array([2, 5]), array([8]), array([10])]

In [71]:
# we split() method but it split equal part otherwise raise error
np.split(arr,3)

ValueError: array split does not result in an equal division

In [72]:
# split equal division
np.split(arr,2)

[array([2, 5]), array([ 8, 10])]

In [73]:
# hsplit - not work in 1d array
np.hsplit(arr_2d,2)

[array([[2, 4],
        [3, 6]]),
 array([[ 6,  8],
        [ 9, 12]])]

In [74]:
# vsplit - not work in 1d array
np.vsplit(arr_2d,2)

[array([[2, 4, 6, 8]]), array([[ 3,  6,  9, 12]])]

In [75]:
# array split 3d array
np.array_split(arr_3d, 2)

[array([[[2, 4, 6, 8],
         [5, 5, 5, 5]]]),
 array([[[ 4,  8,  7, 16],
         [ 5, 10, 15, 20]]])]

In [76]:
# array split use axis for row and column(axis=1)
np.array_split(arr_3d, 2, axis=1)

[array([[[ 2,  4,  6,  8]],
 
        [[ 4,  8,  7, 16]]]),
 array([[[ 5,  5,  5,  5]],
 
        [[ 5, 10, 15, 20]]])]

## Searching in Array

In [77]:
# search index using where()
ar = np.array([2, 3, 4, 6, 8, 9, 10, 12, 14, 15])
search = np.where(ar == 8)

In [78]:
search

(array([4], dtype=int64),)

In [79]:
# search with condition- show even value index
np.where(ar%2==0)

(array([0, 2, 3, 4, 6, 7, 8], dtype=int64),)

In [80]:
# show odd value index
np.where(ar%2==1)

(array([1, 5, 9], dtype=int64),)

## Sorting Array

In [81]:
ar_ = np.array([4,1,3,9,7,15,11,8,18,5])

In [82]:
#sort array - not change in orignal array(make another copy)
np.sort(ar_)

array([ 1,  3,  4,  5,  7,  8,  9, 11, 15, 18])

In [83]:
ar_1 = np.array([[8,3,4,1,7],[4,9,0,5,2]])
ar_1

array([[8, 3, 4, 1, 7],
       [4, 9, 0, 5, 2]])

In [84]:
# sort 2d array
np.sort(ar_1)

array([[1, 3, 4, 7, 8],
       [0, 2, 4, 5, 9]])

In [85]:
# sort 2d array with axis 
# axis = 0 (sort according to column )
np.sort(ar_1, axis = 0)

array([[4, 3, 0, 1, 2],
       [8, 9, 4, 5, 7]])

In [86]:
# sort and display index array(array of index of element)
index_arr = np.argsort(ar_1)
index_arr

array([[3, 1, 2, 4, 0],
       [2, 4, 0, 3, 1]], dtype=int64)

In [87]:
index_arr_ = np.argsort(ar_1, axis=0)
index_arr_

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]], dtype=int64)

In [88]:
# find minimum and maximum value's index
index_min = np.argmin(index_arr)
print(index_min)
index_max = np.argmax(index_arr)
print(index_max)

4
3


## Filter Array

In [89]:
# filter array with condition
%time
filter = ar_ > 5          # true when conditon true otherwise false
filter_ar = ar_[filter]   # array of true value
print(filter)
print(filter_ar)

CPU times: total: 0 ns
Wall time: 0 ns
[False False False  True  True  True  True  True  True False]
[ 9  7 15 11  8 18]


In [90]:
# we can also filter with for loop
%time
filter_ar = []
for a in ar_:
    if a > 5:
        filter_ar.append(a)
print(filter_ar)

CPU times: total: 0 ns
Wall time: 0 ns
[9, 7, 15, 11, 8, 18]


## More

In [91]:
#count nonzeor element 
np.count_nonzero(arr_2d)

8

In [92]:
# difference betweeen size of python list and numpy array
import sys

In [93]:
# defien python list
py_ar = [4,16,34,67]

In [94]:
# define numpy arrray(convert python list to numpy array)
np_ar = np.array(py_ar)

In [95]:
# size of python list
sys.getsizeof(1) * len(py_ar)

112

In [96]:
# size of numpy array
np_ar.itemsize * np_ar.size

16

In [97]:
# convert numpy array to python list
np_ar.tolist()

[4, 16, 34, 67]

In [98]:
# we save any arr in numpy with name
np.save('my_np', np_ar)

In [99]:
# we can use that array any notebook using load and npy extension
new_arr = np.load('my_np.npy')

In [100]:
new_arr

array([ 4, 16, 34, 67])