In [1]:
import numpy as np

# Help

In [2]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Creating arrays

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

## Initial placeholder

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [9]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
# Create a constant array
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [11]:
# Identity matrix
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [12]:
np.random.random((2,2))

array([[0.48671664, 0.48326273],
       [0.28862639, 0.93487606]])

In [13]:
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# Inspection

In [14]:
a.shape

(3,)

In [15]:
len(a)

3

In [16]:
b.ndim

2

In [17]:
e.size

4

In [18]:
b.dtype

dtype('float64')

In [19]:
b.dtype.name

'float64'

In [20]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

# Array Mathematics

## Arithmetic Operations

In [21]:
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [22]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [23]:
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [24]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [25]:
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [26]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [27]:
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [28]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [29]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [30]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [31]:
# Print sines of an array
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [32]:
# Element-wise cosine
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [33]:
# Element-wise natural logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [34]:
# Dot product
e.dot(f)

array([[7., 7.],
       [7., 7.]])

## Comparison

In [35]:
# Element-wise comparison
a == b

array([[False,  True,  True],
       [False, False, False]])

In [36]:
a < 2

array([ True, False, False])

In [37]:
# Array-wise comparison
np.array_equal(a, b)

False

## Aggregate Functions

In [38]:
a.sum()

6

In [39]:
a.min()

1

In [40]:
# Maximum value of an array row
b.max(axis=0)

array([4., 5., 6.])

In [41]:
# Maximum value of an array col
b.max(axis=1)

array([3., 6.])

In [42]:
# Cumulative sum of the elements (row)
b.cumsum(axis=0)

array([[1.5, 2. , 3. ],
       [5.5, 7. , 9. ]])

In [43]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [44]:
a.mean()

2.0

In [45]:
np.median(b)

3.5

In [46]:
# Correlation coefficient
np.corrcoef(a)

1.0

In [47]:
np.std(b)

1.5920810978785667

# Copying Arrays

In [48]:
# Create a view of the array with the same data
h = a.view()
h

array([1, 2, 3])

In [49]:
np.copy(a)

array([1, 2, 3])

In [50]:
h = a.copy()
h

array([1, 2, 3])

# Sorting Arrays

In [51]:
a = np.array([3,2,1])
a.sort()
a

array([1, 2, 3])

In [52]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [53]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c.sort(axis=1)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [54]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c.sort()
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ]]])

# Subsetting, Slicing, Indexing

In [55]:
a[2]

3

In [56]:
b[1,2]

6.0

In [57]:
a[0:2]

array([1, 2])

In [58]:
b[0:2,1]

array([2., 5.])

In [59]:
b[:1]

array([[1.5, 2. , 3. ]])

In [60]:
c[1,...]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [61]:
a[::-1]

array([3, 2, 1])

In [62]:
a[a<2]

array([1])

In [63]:
# Select elements (1,0),(0,1),(1,2) and (0,0)
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [64]:
# Select a subset of the matrix’s rows and cols
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

# Array Manipulation

## Transposing Array

In [65]:
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [66]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Changing Array Shape

In [67]:
# Flatten the array
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [68]:
# Reshape the array
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## Adding/Removing Elements

In [69]:
h.resize((2,6), refcheck=False)
h

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [70]:
np.append(h,g)

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [71]:
np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [72]:
np.delete(a,[1])

array([1, 3])

## Combining Arrays

In [73]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [74]:
# Stack arrays vertically (row-wise)
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [75]:
# Stack arrays vertically (row-wise)
# all the input arrays must have same number of dimensions
np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [76]:
# Stack arrays horizontally (column-wise)
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [77]:
# Create stacked column-wise arrays
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [78]:
# Create stacked column-wise arrays
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

## Splitting Arrays

In [79]:
# Split the array horizontally at the 3rd index
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [80]:
# Split the array vertically at the 2nd index
np.vsplit(c,2)

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]), array([[[1., 2., 3.],
         [4., 5., 6.]]])]