# MATH OPERATIONS NUMPY ARRAY

In [1]:
# import numpy
import numpy as np

In [2]:
# create array
arr = np.array((3, 2, 8, 12))
arr_ = np.array((4, 7, 9, 6))

## Simple Arithmetic

* ### Sum

In [3]:
# sum of two array
arr_sum = arr + arr_

In [4]:
arr_sum

array([ 7,  9, 17, 18])

In [5]:
# sum using add fuction
arr_add = np.add(arr, arr_)

In [6]:
arr_add

array([ 7,  9, 17, 18])

* ### Subtraction

In [7]:
# subtraction
arr_sub = arr_ - arr

In [8]:
arr_sub

array([ 1,  5,  1, -6])

In [9]:
# subtraction using subtract fucntion
arr_subt = np.subtract(arr_, arr)

In [10]:
arr_subt

array([ 1,  5,  1, -6])

* ### Multiplication

In [11]:
arr_mul = arr*arr_

In [12]:
arr_mul

array([12, 14, 72, 72])

In [13]:
# multiplication using mutiply fuction
arr_mul_ = np.multiply(arr, arr_)

In [14]:
arr_mul

array([12, 14, 72, 72])

* ### Division

In [15]:
arr_div = arr / arr_

In [16]:
arr_div

array([0.75      , 0.28571429, 0.88888889, 2.        ])

In [17]:
#division using divide funtion
arr_div_ = np.divide(arr, arr_)

In [18]:
arr_div

array([0.75      , 0.28571429, 0.88888889, 2.        ])

* ### Power

In [19]:
arr_power = arr**2

In [20]:
arr_power

array([  9,   4,  64, 144])

In [21]:
# using power function
arr_pow = np.power(arr, 2)

In [22]:
arr_pow

array([  9,   4,  64, 144], dtype=int32)

In [23]:
# we can also uses arr instead power's value
arr_pow_ = np.power(arr, arr_)

In [24]:
arr_pow_

array([       81,       128, 134217728,   2985984])

* ### Mod

In [25]:
arr_mod = arr%2

In [26]:
arr_mod

array([1, 0, 0, 0], dtype=int32)

In [27]:
# using mod and remainder functions - both are same
# we can also use arr instead of value
ar_mod = np.mod(arr,2)
ar_remain = np.remainder(arr,2)

In [28]:
ar_mod

array([1, 0, 0, 0], dtype=int32)

In [29]:
ar_remain

array([1, 0, 0, 0], dtype=int32)

* ### Quotient and mod(divmod) , Absolute value

In [30]:
# divmod function return both the quotient and mod
arr_qm = np.divmod(arr,2)

In [31]:
arr_qm

(array([1, 1, 4, 6], dtype=int32), array([1, 0, 0, 0], dtype=int32))

In [32]:
# absolute funtion return positive value like abs funtion of math module
abs_ar = [-3, -5, -1, -7, 2]
abso = np.absolute(abs_ar)

In [33]:
abso

array([3, 5, 1, 7, 2])

## Rounding Decimals

* ### Fix and Truncation

In [34]:
# define a floating array
dm_arr = np.array((4.1769, 7.029978, -2.5687))

 fix and trunc both remove the decimal and return float number with 0 decimal

In [35]:
fix = np.fix(dm_arr)

In [36]:
fix

array([ 4.,  7., -2.])

In [37]:
trunc = np.trunc(dm_arr)

In [38]:
trunc

array([ 4.,  7., -2.])

* ### Around funtion

around funtion increments preceding digit by 1 if element's decimal => 5

In [39]:
np.around(dm_arr)

array([ 4.,  7., -3.])

* ### Floor and Ceil

foor function return nearest lower integer,
ceil function return nerest upper integer

In [40]:
np.floor(dm_arr)

array([ 4.,  7., -3.])

In [41]:
np.ceil(dm_arr)

array([ 5.,  8., -2.])

## Summations, Products, Differences

sum the values of array or multiple array

In [42]:
# sum the values of both array
np.sum([arr,arr_])

51

In [43]:
# sum the values of each array. its returns anothr array with sum values
np.sum([arr, arr_], axis=1)

array([25, 26])

* ### Cummulative Sum

Partially adding elements in array 

In [44]:
np.cumsum(arr)

array([ 3,  5, 13, 25])

* ### Product

Product of elemensts of array or multiple array

In [45]:
np.prod(arr)

576

In [46]:
#product of the elements of two arrays
np.prod([arr, arr_])

870912

In [47]:
# product of the elements of each array 
np.prod([arr, arr_], axis=1)

array([ 576, 1512])

* ### Cummulative Product

Partially multiply elements in array 

In [48]:
np.cumprod(arr)

array([  3,   6,  48, 576])

* ### Difference

Subract two successive elements

In [49]:
np.diff(arr)

array([-1,  6,  4])

In [50]:
# n = vlaue, if we want difference multiple time 
# here second time =  6-(-1), 4-6
np.diff(arr, n=2)

array([ 7, -2])

## Logs

log2 fucntion - perform log at base 2

In [51]:
np.log2(arr)

array([1.5849625, 1.       , 3.       , 3.5849625])

log10 function - perform log at base 10

In [52]:
np.log10(arr)

array([0.47712125, 0.30103   , 0.90308999, 1.07918125])

log fuction - perform log at base e

In [53]:
np.log(arr)

array([1.09861229, 0.69314718, 2.07944154, 2.48490665])

* ### Log at Any Base

Numpy does not have any function to take log at any base <br>
We can create own function using <b>frompyfunc</b> inbuilt function with math.log module<br>
<b>frompyfunc[function, input, output]<b>
    <ol>
        <li>function - name of function or mehod, which we use for creating own fucntion</li>
        <li>input - number of input arguments</li>
        <li>output - number of output</li>
    </ol>

In [54]:
from math import log
logN = np.frompyfunc(log,2,1)
#here 2 argument- one value or array, one base

In [55]:
logN(50,15)

1.4445902826453896

In [56]:
logN(arr,13)

array([0.42831734103139474, 0.27023815442731974, 0.8107144632819592,
       0.9687936498860342], dtype=object)

## LCM (Lowest Common Multiple)

In [57]:
np.lcm(12,20)

60

In [58]:
# to find lcm of array  
np.lcm.reduce(arr)

24

## GCD (Greatest Common Denominator)

In [59]:
np.gcd(12,20)

4

In [60]:
# to find gcd of array
np.gcd.reduce(arr)

1

## Trigonometric Functions

Numpy provides <b>sin, cos, tan</b> function

In [61]:
# sin, cos, tan vlaue of pi/2
sin = np.sin(np.pi/2)
cos = np.cos(np.pi/2)
tan = np.tan(np.pi/2)

In [62]:
sin

1.0

In [63]:
cos

6.123233995736766e-17

In [64]:
tan

1.633123935319537e+16

In [65]:
# sin values of array
np.sin(arr)

array([ 0.14112001,  0.90929743,  0.98935825, -0.53657292])

Convert values to degrees

In [66]:
np.rad2deg(arr)

array([171.88733854, 114.59155903, 458.3662361 , 687.54935416])

In [67]:
deg = np.array([30, 180, 270, 135])

Convert degree arr to radians

In [68]:
np.deg2rad(deg)

array([0.52359878, 3.14159265, 4.71238898, 2.35619449])

* ### Hyperbolic Functions

Numpy provides sinh, cosh, tanh functions

In [69]:
np.sinh(np.pi/2)

2.3012989023072947

In [70]:
np.cosh(np.pi/2)

2.5091784786580567

In [71]:
np.tanh(np.pi/2)

0.9171523356672744

* ### Find Angle

finding angles from values of sine, cos and tan

In [72]:
np.arcsin(1.0)

1.5707963267948966

In [73]:
np.arccos(1.0)

0.0

In [74]:
np.arctan(1.0)

0.7853981633974483

finding angles from values of sinh, cosh and tanh

In [75]:
np.arcsinh(2.3)

1.5702785434849782

In [76]:
np.arcsinh(2.5)

1.6472311463710958

In [77]:
np.arcsinh(1.0)

0.881373587019543

* ### Find Hypotenues

finding hypotenues using pythagoras theorem 

In [78]:
# hypot function take two value base and perpendicular
np.hypot(4,3)

5.0

## Set Operations

union1d method - find unique values fo two arrays

In [79]:
np.union1d(arr,arr_)

array([ 2,  3,  4,  6,  7,  8,  9, 12])

intersect1d method - find only the values that are present in both arrays

In [80]:
np.intersect1d(arr,arr_)

array([], dtype=int32)

In [81]:
np.intersect1d([3,4,1],[7,3,2])

array([3])

unique method - find unique elements from an array

In [82]:
np.unique(arr)

array([ 2,  3,  8, 12])

* ### Find Difference

find only the values in first array that is not present in second array<br>
   <b>setdiff1d<b/> fucntion

In [83]:
set_arr = np.array([4,3,9,12])
set_arr_ = np.array([5,2,10,9])

In [84]:
np.setdiff1d(set_arr, set_arr_)

array([ 3,  4, 12])

* ### Find Symmetric Difference

find only the values that are not present in both set(array)<br>
<b>setxor1d</b> method

In [85]:
np.setxor1d(set_arr, set_arr_)

array([ 2,  3,  4,  5, 10, 12])

## Statistics

* ### Mean funtion

find average of array

In [86]:
sts_arr = np.array([5,9,12,23,25])

In [87]:
np.mean(sts_arr)

14.8

* ### median

find midle element of array

In [88]:
np.median(sts_arr)

12.0

When two element in midle, its automatically calculate average of that elements<br>
<b>(midle element + midle element)/2</b>

In [89]:
sts_arr_ = np.array([8,10,12,15,19,22])

In [90]:
np.median(sts_arr_)

13.5

In [91]:
np.average([12,15])

13.5

* ## Variance

Variance = sum of square of diffrence of mean and each elements<br>
<b>var = (mean-first)**2 + (mean-second)**2 + ............+(mean-n)**2</b>

In [92]:
var = np.var(sts_arr)

In [93]:
var

61.76000000000001

* ### Standard Deviation

Standard Deviation = square root of variance<br>
<b>std = sqrt(var)</b>

In [94]:
np.std(sts_arr)

7.858753081755401

In [95]:
np.sqrt(var)

7.858753081755401