## Random Number

Numpy provides random module to wrok with random numbers

In [4]:
import numpy as np
from numpy import random

* ### randint() method

* randint() method return integer random value

In [7]:
# random value under 100
random.randint(100)

95

* randint() method take a size parameter as shape of array

In [8]:
# 1d array with 5 element
random.randint(100, size=5)

array([95, 44, 48, 33, 78])

In [10]:
# 2d array with 5 element
random.randint(100, size=(2,5))

array([[92, 96, 82, 45, 29],
       [27, 42, 76, 20, 96]])

* ### rand() method

* rand() method return float random value between 0 to 1

In [12]:
random.rand()

0.3253287653947502

In [13]:
# 1d array with 5 elements
random.rand(5)

array([0.85261751, 0.42144015, 0.49604113, 0.23865416, 0.23492317])

In [14]:
# 2d array with 5 elements
random.rand(2,5)

array([[0.32017264, 0.26959633, 0.49578483, 0.69801676, 0.38472602],
       [0.48098279, 0.17779158, 0.05597304, 0.17831558, 0.95910167]])

* ### choice() method

* choice method generate a random value based on array

In [16]:
arr = np.array([2, 9, 12, 15])

In [17]:
random.choice(arr)

12

* choice method takes size parameter to define shape of array

In [18]:
random.choice(arr, size = (3,5))

array([[12, 15,  9,  2,  2],
       [15,  2,  9,  9,  9],
       [12,  2, 15, 15,  9]])

* choice method takes probability(p) parameter of each value of array for data distributions <br>
* probability sum should be 1 (means 100%)

In [29]:
random.choice(arr, p=[0.4, 0.3, 0.2,0.1], size=(2,5))

array([[ 2,  2,  2,  9,  2],
       [ 9,  9, 15,  2,  2]])

* ### permutation() and shuffle() method

* both method refers to an random arrangement of elements of given array

* <b>permutation()</b> method return re-arranged array but original array unchanged

In [31]:
random.permutation(arr)

array([15,  9,  2, 12])

In [32]:
# original array
arr

array([ 2,  9, 12, 15])

* <b>shuffle</b> method re-arranged original array

In [35]:
arr_ = np.array([4,8,10,5])

In [39]:
random.shuffle(arr_)

In [40]:
arr_

array([ 5, 10,  4,  8])